# =============================================================================
# Study Service Only - For development when infrastructure is already running
# =============================================================================
# This compose file starts only the study service
# Use this when MySQL, Redis, and Eureka are already running from core-platform
# =============================================================================

services:
  # Study Service - Study Management and Proposal System
  study-service:
    build:
      context: .
      dockerfile: Dockerfile
    image: asyncsite/study-service:latest
    container_name: asyncsite-study-service
    restart: unless-stopped
    ports:
      - "8083:8083"
    environment:
      # Spring Configuration
      - SPRING_PROFILES_ACTIVE=docker
      
      # Service Discovery (uses shared Eureka)
      - EUREKA_CLIENT_ENABLED=true
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://asyncsite-eureka:8761/eureka/
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
      - EUREKA_INSTANCE_INSTANCE_ID=${HOSTNAME}:study-service:8083
      - EUREKA_INSTANCE_METADATA_MAP_VERSION=1.0.0
      - EUREKA_INSTANCE_METADATA_MAP_ZONE=docker
      
      # Database Configuration (uses shared MySQL)
      - SPRING_DATASOURCE_URL=jdbc:mysql://asyncsite-mysql:3306/studydb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&characterEncoding=utf8&useUnicode=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=asyncsite_root_2024!
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
      
      # JPA/Hibernate Configuration
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=false
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQLDialect
      - SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL=false
      
      # Logging Configuration
      - LOGGING_LEVEL_COM_ASYNCSITE_STUDYSERVICE=INFO
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY=INFO
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB=INFO
      
      # Management and Health
      - MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE=health,info,metrics
      - MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS=always
      - MANAGEMENT_HEALTH_DB_ENABLED=true
    
    # Health check configuration
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8083/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    
    # Resource limits
    deploy:
      resources:
        limits:
          memory: 768M
          cpus: '1.0'
        reservations:
          memory: 384M
          cpus: '0.5'
    
    # Labels for service identification
    labels:
      - "com.asyncsite.service=study-service"
      - "com.asyncsite.tier=business"
      - "com.asyncsite.type=microservice"
      - "com.asyncsite.domain=study"

    volumes:
      - ~/asyncsite-logs/study-service:/app/logs

# =============================================================================
# Network Configuration
# =============================================================================
networks:
  default:
    external: true
    name: asyncsite-network

volumes:
  study-service-logs:
    driver: local
