# Docker Profile Configuration for Study Service
spring:
  application:
    name: study-service
  
  # Database Configuration (uses shared MySQL from Core Platform)
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://asyncsite-mysql:3306/studydb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&characterEncoding=utf8&useUnicode=true}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:asyncsite_root_2024!}
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  # JPA/Hibernate Configuration
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    show-sql: ${SPRING_JPA_SHOW_SQL:false}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: ${SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL:false}

# Server Configuration
server:
  port: 8083

# Eureka Configuration (uses shared Eureka from Core Platform)
eureka:
  client:
    enabled: ${EUREKA_CLIENT_ENABLED:true}
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE:http://asyncsite-eureka:8761/eureka/}
  instance:
    prefer-ip-address: ${EUREKA_INSTANCE_PREFER_IP_ADDRESS:true}
    instance-id: ${EUREKA_INSTANCE_INSTANCE_ID:${HOSTNAME}:study-service:8083}
    metadata-map:
      version: ${EUREKA_INSTANCE_METADATA_MAP_VERSION:1.0.0}
      zone: ${EUREKA_INSTANCE_METADATA_MAP_ZONE:docker}

# Management and Health Configuration
management:
  endpoints:
    web:
      exposure:
        include: ${MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE:health,info,metrics}
  endpoint:
    health:
      show-details: ${MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS:always}
  health:
    db:
      enabled: ${MANAGEMENT_HEALTH_DB_ENABLED:true}

# Logging Configuration
logging:
  level:
    root: ${LOGGING_LEVEL_ROOT:INFO}
    com.asyncsite.studyservice: ${LOGGING_LEVEL_COM_ASYNCSITE_STUDYSERVICE:INFO}
    org.springframework.security: ${LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY:INFO}
    org.springframework.web: ${LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB:INFO}
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n'