spring:
  application:
    name: study-service
  
  # Spring Cloud Compatibility
  cloud:
    compatibility-verifier:
      enabled: false
  
  # Database Configuration (MySQL for local development)
  datasource:
    url: jdbc:mysql://localhost:3306/studydb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: asyncsite_root_2024!
  
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        jdbc:
          time_zone: UTC

# Eureka Configuration - Disable for local testing
eureka:
  client:
    enabled: false

# Swagger/OpenAPI Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: alpha
    tags-sorter: alpha
    try-it-out-enabled: true
    display-query-params-without-oauth2: true

# Server Configuration
server:
  port: 8080

# Management endpoints for local monitoring
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env,configprops
  endpoint:
    health:
      show-details: always

# Logging Configuration for local development
logging:
  level:
    com.asyncsite.studyservice: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
