name: CI/CD Pipeline

on:
  push:
    branches: [ main, feature/**, fix/**, release/**, hotfix/** ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  DOCKER_REGISTRY: ghcr.io
  IMAGE_NAME: ghcr.io/asyncsite/study-service

permissions:
  contents: read
  checks: write
  pull-requests: write
  packages: write

jobs:
  test:
    name: Build and Test
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout study-service
      uses: actions/checkout@v4
      with:
        path: study-service
        fetch-depth: 0
    
    - name: Checkout core-platform
      uses: actions/checkout@v4
      with:
        repository: AsyncSite/core-platform
        ref: feature/common/initial-setup
        path: core-platform
        token: ${{ secrets.PAT_TOKEN }}
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'gradle'
    
    - name: Build and publish core-platform common module
      working-directory: core-platform
      run: |
        chmod +x gradlew
        ./gradlew :common:build --no-daemon
        ./gradlew :common:publishToMavenLocal --no-daemon
        echo "Common module published to:"
        ls -la ~/.m2/repository/com/asyncsite/coreplatform/common/
    
    - name: Grant execute permission for gradlew
      working-directory: study-service
      run: chmod +x gradlew
    
    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    
    - name: Configure Gradle properties
      working-directory: study-service
      run: |
        mkdir -p ~/.gradle
        echo "gpr.user=${{ github.actor }}" >> ~/.gradle/gradle.properties
        echo "gpr.key=${{ secrets.GITHUB_TOKEN }}" >> ~/.gradle/gradle.properties
        
    - name: Build with Gradle (skip tests)
      working-directory: study-service
      run: ./gradlew build -x test --no-daemon --stacktrace
      env:
        USERNAME: ${{ github.actor }}
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Run tests
      working-directory: study-service
      run: ./gradlew test --no-daemon --stacktrace
      env:
        USERNAME: ${{ github.actor }}
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: '**/build/test-results/test/'
        retention-days: 7
    
    - name: Upload test reports
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-reports
        path: '**/build/reports/tests/'
        retention-days: 7

  build-and-push:
    name: Build and Push Docker Image
    needs: test
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'push' && 
      (contains(github.ref, 'main') || contains(github.ref, 'feature/'))
    
    steps:
    - name: Checkout study-service
      uses: actions/checkout@v4
      with:
        path: study-service
        fetch-depth: 0
    
    - name: Checkout core-platform
      uses: actions/checkout@v4
      with:
        repository: AsyncSite/core-platform
        ref: feature/common/initial-setup
        path: core-platform
        token: ${{ secrets.PAT_TOKEN }}
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'gradle'
    
    - name: Build and publish core-platform common module
      working-directory: core-platform
      run: |
        chmod +x gradlew
        ./gradlew :common:build --no-daemon
        ./gradlew :common:publishToMavenLocal --no-daemon
    
    - name: Configure Gradle properties
      working-directory: study-service
      run: |
        mkdir -p ~/.gradle
        echo "gpr.user=${{ github.actor }}" >> ~/.gradle/gradle.properties
        echo "gpr.key=${{ secrets.GITHUB_TOKEN }}" >> ~/.gradle/gradle.properties
    
    - name: Build application
      working-directory: study-service
      run: |
        chmod +x gradlew
        ./gradlew build -x test --no-daemon
      env:
        USERNAME: ${{ github.actor }}
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.DOCKER_REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./study-service
        file: ./study-service/Dockerfile
        push: true
        tags: |
          ${{ env.IMAGE_NAME }}:latest
          ${{ env.IMAGE_NAME }}:${{ github.sha }}

  deploy:
    name: Deploy to Home Server
    needs: build-and-push
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'push' && 
      (contains(github.ref, 'main') || contains(github.ref, 'feature/'))
    
    steps:
    - name: Setup SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" | base64 -d > ~/.ssh/deploy_key
        chmod 600 ~/.ssh/deploy_key
        ssh-keyscan -p 2222 -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
    
    - name: Deploy to server
      run: |
        ssh -p 2222 -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'ENDSSH'
          echo "Starting deployment of study-service..."
          
          # Navigate to deployment directory
          cd ~/deployments/study-service || mkdir -p ~/deployments/study-service && cd ~/deployments/study-service
          
          # Create docker-compose file
          cat > docker-compose.yml << COMPOSE_EOF
          services:
            study-service:
              image: ${{ env.IMAGE_NAME }}:${{ github.sha }}
              container_name: asyncsite-study-service
              ports:
                - "8083:8083"
              environment:
                - SPRING_PROFILES_ACTIVE=docker
                - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://asyncsite-eureka:8761/eureka/
                - SPRING_DATASOURCE_URL=jdbc:mysql://asyncsite-mysql:3306/studydb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&characterEncoding=utf8&useUnicode=true
                - SPRING_DATASOURCE_USERNAME=root
                - SPRING_DATASOURCE_PASSWORD=asyncsite_root_2024!
              networks:
                - asyncsite-network
              restart: unless-stopped
              healthcheck:
                test: ["CMD", "curl", "-f", "http://localhost:8083/actuator/health"]
                interval: 30s
                timeout: 10s
                retries: 3
                start_period: 60s
          
          networks:
            asyncsite-network:
              external: true
        COMPOSE_EOF
          
          # Login to GitHub Container Registry
          echo "${{ secrets.PAT_TOKEN }}" | docker login ghcr.io -u renechoi --password-stdin
          
          # Pull latest image
          docker pull ${{ env.IMAGE_NAME }}:${{ github.sha }}
          
          # Stop and remove old containers
          docker compose down --remove-orphans || true
          
          # Start new containers
          docker compose up -d
          
          # Wait for services to be healthy
          echo "Waiting for services to be healthy..."
          sleep 45
          
          # Check service status
          docker ps | grep asyncsite-study-service
          
          echo "Deployment completed!"
        ENDSSH