name: PR Check

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write
  checks: write

jobs:
  pr-validation:
    name: PR Validation
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout study-service
      uses: actions/checkout@v4
      with:
        path: study-service
        fetch-depth: 0
    
    - name: Checkout core-platform
      uses: actions/checkout@v4
      with:
        repository: AsyncSite/core-platform
        ref: feature/common/initial-setup
        path: core-platform
        token: ${{ secrets.PAT_TOKEN }}
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'gradle'
    
    - name: Build and publish core-platform common module
      working-directory: core-platform
      run: |
        chmod +x gradlew
        ./gradlew :common:build --no-daemon
        ./gradlew :common:publishToMavenLocal --no-daemon
    
    - name: Grant execute permission for gradlew
      working-directory: study-service
      run: chmod +x gradlew
    
    - name: Validate Gradle wrapper
      working-directory: study-service
      uses: gradle/wrapper-validation-action@v2
      continue-on-error: true
    
    - name: Configure Gradle properties
      working-directory: study-service
      run: |
        mkdir -p ~/.gradle
        echo "gpr.user=${{ github.actor }}" >> ~/.gradle/gradle.properties
        echo "gpr.key=${{ secrets.GITHUB_TOKEN }}" >> ~/.gradle/gradle.properties
    
    - name: Build project
      working-directory: study-service
      run: ./gradlew build -x test --no-daemon
      env:
        USERNAME: ${{ github.actor }}
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Run unit tests
      working-directory: study-service
      run: ./gradlew test --no-daemon
      env:
        USERNAME: ${{ github.actor }}
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Add test results to PR
      if: always()
      run: |
        echo "## PR Test Results" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        if [ $? -eq 0 ]; then
          echo "✅ All tests passed!" >> $GITHUB_STEP_SUMMARY
        else
          echo "❌ Some tests failed. Check the logs for details." >> $GITHUB_STEP_SUMMARY
        fi